# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant-aws'

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider "aws" do |aws, override|
    # AWS credentials
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']

    # AWS region and AMI
    aws.region = "us-east-1"
    aws.ami = "ami-054d6a336762e438e"

    # Instance type
    aws.instance_type = "t3.xlarge"

    # Key pair for SSH
    aws.keypair_name = "api-server"
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = File.expand_path("api-server.pem", __dir__)

    # Network settings
    aws.subnet_id = "subnet-0a03e0dbddc93b6aa"
    aws.associate_public_ip = true
    aws.security_groups = ["sg-09d4c5f5679711dd2"]

    # Do not terminate instance on shutdown
    aws.terminate_on_shutdown = false
  end
end
