apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault-service.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: "external-secrets"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: studentdb-secrets
  namespace: student-api
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: "vault-backend"
    kind: "ClusterSecretStore"
  target:
    name: "postgres-secret"
    creationPolicy: "Owner"
  data:
    - secretKey: "POSTGRES_USER"
      remoteRef:
        key: "studentdb"
        property: "POSTGRES_USER"
    - secretKey: "POSTGRES_PASSWORD"
      remoteRef:
        key: "studentdb"
        property: "POSTGRES_PASSWORD"
